name: PR Build Check

on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**/*.md'
      - '**/*.yml'
  pull_request:
    branches: [ 'master' ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**/*.md'
      - '**/*.yml'

jobs:
  build-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Install Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 22.13.1
          cache: npm

      - name: Install project dependencies
        run: npm ci

      - name: Build Vite (verify only)
        run: npm run build
